# Generated by Django 5.1.1 on 2024-09-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_workload", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferenceresult",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="inferenceresult",
            name="result_names_comma_separated",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
