# Generated by Django 5.1.1 on 2024-09-26 18:12

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20240906_1420"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diet",
            name="image",
            field=models.ImageField(upload_to=users.models.diet_image_path),
        ),
    ]
