# Generated by Django 5.1.1 on 2024-10-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_hospitalalarm_pillalarm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pillalarm",
            name="user",
        ),
        migrations.DeleteModel(
            name="HospitalAlarm",
        ),
        migrations.DeleteModel(
            name="PillAlarm",
        ),
    ]
