# Generated by Django 5.1.2 on 2024-10-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_pillalarm_user_delete_hospitalalarm_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodCalories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(max_length=100)),
                ("energy_kcal", models.IntegerField()),
                ("weight_g", models.IntegerField()),
                ("carbohydrates_g", models.FloatField()),
                ("protein_g", models.FloatField()),
                ("fat_g", models.FloatField()),
                ("diabetes_risk_classification", models.IntegerField()),
            ],
        ),
    ]
